server:
  port: 8084
spring:
  cloud:
    gateway:
      routes:
        - predicates:
            - Path=/java/**
          filters:
            - name: GpDefine
              args:
                - name: Gp_Mic
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                denyEmptyKey: true
                emptyKeyStatus: SERVICE_UNAVAILABLE
                key-resolver: '#{@hostAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 3
          uri: "http://localhost:8083/hello"
  application:
    name: spring-cloud-gateway-sample
  redis:
    host: 192.168.6.109
    port: 6379
#    database: 0

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
